import React, { useState } from 'react';
import { 
  Sparkles, Compass, Calendar, Search, MapPin, 
  ArrowRight, Loader2, CheckCircle2, Clock, Layers 
} from 'lucide-react';

export default function AiTravelFrontend() {
  // --- STATE LAYER ---
  const [step, setStep] = useState('wizard'); // 'wizard' or 'loading' or 'dashboard'
  const [destination, setDestination] = useState('');
  const [duration, setDuration] = useState('3');
  const [vibe, setVibe] = useState('chill-foodie');
  const [activeDayId, setActiveDayId] = useState('day-1');

  // This state holds the raw JSON payload generated by the backend Zod scheme
  const [generatedData, setGeneratedData] = useState(null);

  // --- MOCK API CALL HANDLER ---
  const handleGenerate = () => {
    setStep('loading');
    
    // Simulate your backend Node.js model calculation (takes ~2.5 seconds)
    setTimeout(() => {
      const mockBackendPayload = {
        tripName: `${vibe.replace('-', ' ').toUpperCase()} in ${destination || 'Paris'}`,
        days: [
          {
            id: "day-1",
            title: "Day 1: Micro-Bakeries & Walks",
            desc: "Focus on tasting profiles & low-impact strolling",
            clusterName: "Marais Historic District Cluster",
            walkingTime: "11 mins total walk",
            stops: [
              { time: "09:30", name: "Croissant Run at Tout Autour du Pain", addr: "134 Rue de Turenne", status: "completed" },
              { time: "11:00", name: "Place des Vosges Garden Walk", addr: "Place des Vosges", status: "active" },
              { time: "13:00", name: "AI Suggested: L'As du Fallafel", addr: "34 Rue des Rosiers", status: "pending" }
            ]
          },
          {
            id: "day-2",
            title: "Day 2: Hidden Art Collections",
            desc: "Quiet museums away from massive crowds",
            clusterName: "3rd Arrondissement Cluster",
            walkingTime: "14 mins total walk",
            stops: [
              { time: "10:00", name: "Musée Picasso Paris", addr: "5 Rue de Thorigny", status: "pending" },
              { time: "13:30", name: "Lunch at Marché des Enfants Rouges", addr: "39 Rue de Bretagne", status: "pending" }
            ]
          }
        ]
      };
      
      setGeneratedData(mockBackendPayload);
      setStep('dashboard');
    }, 2500);
  };

  return (
    <div className="min-h-screen bg-slate-50 text-slate-900 font-sans antialiased p-4 md:p-8">
      <div className="max-w-[1400px] mx-auto">

        {/* ======================================================= */}
        {/* VIEW 1: THE INPUT WIZARD                                */}
        {/* ======================================================= */}
        {step === 'wizard' && (
          <div className="max-w-md mx-auto mt-12 bg-white rounded-2xl border border-slate-200 shadow-xl overflow-hidden">
            <div className="p-6 bg-slate-900 text-white text-center space-y-2">
              <div className="inline-flex h-10 w-10 items-center justify-center rounded-xl bg-indigo-600">
                <Sparkles className="h-5 w-5 text-white" />
              </div>
              <h2 className="text-xl font-bold tracking-tight">AI Travel Engine</h2>
              <p className="text-xs text-slate-400">Input your core parameters to compute an optimized route.</p>
            </div>

            <div className="p-6 space-y-4">
              {/* Destination Parameter */}
              <div className="space-y-1.5">
                <label className="text-xs font-semibold text-slate-600 uppercase tracking-wider">Where to?</label>
                <div className="relative">
                  <MapPin className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" />
                  <input 
                    type="text" 
                    placeholder="e.g. Paris, Tokyo, New York" 
                    value={destination}
                    onChange={(e) => setDestination(e.target.value)}
                    className="w-full h-10 rounded-lg bg-slate-50 pl-10 pr-4 text-sm border border-slate-200 focus:border-indigo-600 focus:bg-white outline-none transition"
                  />
                </div>
              </div>

              {/* Duration Matrix selector */}
              <div className="space-y-1.5">
                <label className="text-xs font-semibold text-slate-600 uppercase tracking-wider">Duration (Days)</label>
                <select 
                  value={duration} 
                  onChange={(e) => setDuration(e.target.value)}
                  className="w-full h-10 rounded-lg bg-slate-50 px-3 text-sm border border-slate-200 focus:border-indigo-600 focus:bg-white outline-none transition"
                >
                  <option value="1">1 Day Crash Course</option>
                  <option value="2">2 Days Weekend Trip</option>
                  <option value="3">3 Days Standard Getaway</option>
                </select>
              </div>

              {/* Vibe Profiler selection */}
              <div className="space-y-1.5">
                <label className="text-xs font-semibold text-slate-600 uppercase tracking-wider">Your Travel Style</label>
                <select 
                  value={vibe} 
                  onChange={(e) => setVibe(e.target.value)}
                  className="w-full h-10 rounded-lg bg-slate-50 px-3 text-sm border border-slate-200 focus:border-indigo-600 focus:bg-white outline-none transition"
                >
                  <option value="chill-foodie">Slow Paced • Hidden Bakeries & Cafes</option>
                  <option value="culture-speedrun">High Intensity • Iconic Landmarks & Museums</option>
                  <option value="nightlife-bars">Late Night • Jazz Clubs & Speakeasies</option>
                </select>
              </div>

              {/* Execution Action Button */}
              <button 
                onClick={handleGenerate}
                className="w-full h-11 bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg text-sm font-semibold transition shadow-md shadow-indigo-600/10 flex items-center justify-center gap-2 mt-2"
              >
                <span>Generate Optimized Layout</span>
                <ArrowRight className="h-4 w-4" />
              </button>
            </div>
          </div>
        )}

        {/* ======================================================= */}
        {/* VIEW 2: THE INTERMEDIATE LOADING ENGINE                  */}
        {/* ======================================================= */}
        {step === 'loading' && (
          <div className="max-w-sm mx-auto mt-32 text-center space-y-4 p-8 bg-white rounded-2xl border border-slate-100 shadow-sm">
            <Loader2 className="h-8 w-8 text-indigo-600 animate-spin mx-auto" />
            <div className="space-y-1">
              <h4 className="font-bold text-slate-800 text-sm">Structuring JSON Object...</h4>
              <p className="text-xs text-slate-400 max-w-[240px] mx-auto">
                Enforcing Zod schema parameters and grouping neighborhood geocodes dynamically.
              </p>
            </div>
          </div>
        )}

        {/* ======================================================= */}
        {/* VIEW 3: THE POPULATED DASHBOARD OUTPUT                  */}
        {/* ======================================================= */}
        {step === 'dashboard' && generatedData && (
          <div className="space-y-6">
            
            {/* Context Breadcrumb Navigation header block */}
            <div className="flex justify-between items-center bg-white p-4 rounded-xl border border-slate-200 shadow-sm">
              <div className="space-y-0.5">
                <span className="text-[10px] font-bold uppercase tracking-wider text-indigo-600">Calculated Trip Output</span>
                <h2 className="text-xl font-bold tracking-tight">{generatedData.tripName}</h2>
              </div>
              <button 
                onClick={() => setStep('wizard')}
                className="text-xs font-semibold px-3 py-1.5 bg-slate-100 text-slate-600 rounded-lg hover:bg-slate-200 border border-slate-200 transition"
              >
                Reset Parameters
              </button>
            </div>

            {/* Render Three Column Split-view using data array inputs */}
            <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
              
              {/* COLUMN 1: Step 1 Full Map Day Picker tabs */}
              <div className="lg:col-span-3 space-y-2">
                <span className="text-[11px] font-bold uppercase tracking-wider text-slate-400 block px-1">
                  Step 1: Generated List
                </span>
                {generatedData.days.map((day) => {
                  const isSelected = day.id === activeDayId;
                  return (
                    <div 
                      key={day.id}
                      onClick={() => setActiveDayId(day.id)}
                      className={`p-3.5 rounded-xl border cursor-pointer bg-white transition-all text-left ${
                        isSelected ? 'border-indigo-600 ring-2 ring-indigo-500/5 shadow-sm' : 'border-slate-200 hover:border-slate-300'
                      }`}
                    >
                      <h4 className={`text-xs font-bold ${isSelected ? 'text-indigo-600' : 'text-slate-700'}`}>{day.title}</h4>
                      <p className="text-[11px] text-slate-400 mt-0.5 truncate">{day.desc}</p>
                    </div>
                  );
                })}
              </div>

              {/* COLUMN 2: Step 3 Active Day Timeline Card view */}
              <div className="lg:col-span-5 space-y-2">
                <span className="text-[11px] font-bold uppercase tracking-wider text-slate-400 block px-1">
                  Step 3: Selected Execution Stream
                </span>
                
                {/* Find current timeline nodes dynamically */}
                {(() => {
                  const dayObj = generatedData.days.find(d => d.id === activeDayId);
                  return (
                    <div className="bg-white rounded-xl border border-slate-200 shadow-sm p-5 relative before:absolute before:left-9 before:top-6 before:bottom-6 before:w-0.5 before:bg-slate-100">
                      {dayObj.stops.map((stop, index) => (
                        <div key={index} className="relative pl-8 pb-5 last:pb-0">
                          
                          {/* Timeline dynamic icons based on completion states */}
                          <div className={`absolute left-[10px] top-1 h-3.5 w-3.5 rounded-full ring-4 ring-white flex items-center justify-center ${
                            stop.status === 'completed' ? 'bg-emerald-500' : 
                            stop.status === 'active' ? 'bg-indigo-600 animate-pulse' : 'bg-slate-300'
                          }`}>
                            {stop.status === 'completed' && <CheckCircle2 className="h-2 w-2 text-white stroke-[3]" />}
                          </div>

                          <div className="text-[11px] font-mono text-slate-400">{stop.time}</div>
                          <div className="mt-1 p-2.5 rounded-lg bg-slate-50 border border-slate-100">
                            <h5 className="text-xs font-bold text-slate-800">{stop.name}</h5>
                            <p className="text-[11px] text-slate-500 mt-0.5">{stop.addr}</p>
                          </div>
                        </div>
                      ))}
                    </div>
                  );
                })()}
              </div>

              {/* COLUMN 3: Step 2 Cluster Verification Map panel block */}
              <div className="lg:col-span-4 space-y-2">
                <span className="text-[11px] font-bold uppercase tracking-wider text-slate-400 block px-1">
                  Step 2: Geography Cluster Validation
                </span>
                
                {(() => {
                  const dayObj = generatedData.days.find(d => d.id === activeDayId);
                  return (
                    <div className="bg-white rounded-xl border border-slate-200 shadow-sm p-4 space-y-3">
                      <div className="space-y-1">
                        <div className="text-[10px] bg-indigo-50 text-indigo-700 font-bold px-1.5 py-0.5 rounded uppercase inline-block">
                          {dayObj.clusterName}
                        </div>
                        <p className="text-xs text-slate-500 leading-relaxed">
                          These endpoints are isolated within a tight matrix bounding box to restrict transit strain. Total required on foot activity: **{dayObj.walkingTime}**.
                        </p>
                      </div>

                      {/* Graphic simulation layout space placeholder */}
                      <div className="h-[180px] bg-slate-900 rounded-lg flex items-center justify-center relative overflow-hidden border border-slate-800">
                        <div className="absolute inset-0 opacity-10 bg-[radial-gradient(#ffffff_1px,transparent_1px)] [background-size:12px_12px]" />
                        <span className="text-[10px] text-slate-500 font-mono tracking-widest uppercase">
                          Rendering Map Canvas Layer
                        </span>
                      </div>
                    </div>
                  );
                })()}
              </div>

            </div>
          </div>
        )}

      </div>
    </div>
  );
}